<a href="https://colab.research.google.com/github/Ramprasath2000/Data-pipeline-for-Amazon-Customer-Review-Analysis/blob/main/amazon_data_sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("/content/aws_data - Sheet1.csv")

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.isnull().sum()

review_date          0
marketplace          0
customer_id          0
review_id            0
product_id           0
product_parent       0
product_title        0
product_category     0
star_rating          0
helpful_votes        0
total_votes          0
vine                 0
verified_purchase    0
review_headline      0
review_body          0
dtype: int64

In [ ]:
# Check for empty strings, "NA", "NaN", etc.
hidden_nulls = df.apply(lambda x: x.astype(str).str.contains("NA|NaN|n/a|^$", na=False))
print("Potential hidden 'null' strings:")
print(hidden_nulls.sum())

Potential hidden 'null' strings:
review_date          0
marketplace          0
customer_id          0
review_id            0
product_id           0
product_parent       0
product_title        0
product_category     0
star_rating          0
helpful_votes        0
total_votes          0
vine                 0
verified_purchase    0
review_headline      0
review_body          0
dtype: int64

In [ ]:
df.info()

In [ ]:
#converting to standard date time
df["review_date"] = pd.to_datetime(df["review_date"])

#if it is in object it will be usefull
# Extract date components
df['review_year'] = df['review_date'].dt.year
df['review_month'] = df['review_date'].dt.month
#cusotmer id
df["customer_id"] = df["customer_id"].astype(object)
#only 3 values exist so it is better to use category
df["marketplace"] = df["marketplace"].astype("category")
df["product_category"] = df["product_category"].astype("category")
df["product_parent"] = df["product_parent"].astype("int64")
# display(df["product_category"].unique())

In [ ]:
# Then keep only the date component
df["review_date"] = df["review_date"].dt.date

In [ ]:
#standardisation check
print("Unique Product Categories:")
print(df["product_category"].unique())

print("\nUnique Marketplaces:")
print(df["marketplace"].unique())

Unique Product Categories:
['Books', 'Music', 'Video']
Categories (3, object): ['Books', 'Music', 'Video']

Unique Marketplaces:
['US']
Categories (1, object): ['US']

In [ ]:
#backing up the original to preserve readability
df['review_body_raw'] = df['review_body']
df['review_headline'] = df['review_headline']

In [ ]:
#standarzing to lower case
df['review_body'] = df['review_body'].str.lower()
df['review_headline'] = df['review_headline'].str.lower()

In [ ]:
#removing punctuations
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df['review_body'] = df['review_body'].apply(remove_punctuation)
df['review_headline'] = df['review_headline'].apply(remove_punctuation)

In [ ]:
#remove whitespaces
df['review_body'] = df['review_body'].str.strip().replace(r'\s+', ' ', regex=True)
df['review_headline'] = df['review_headline'].str.strip().replace(r'\s+', ' ', regex=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 150
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   review_date        150 non-null    datetime64[ns]
 1   marketplace        150 non-null    category
 2   customer_id        150 non-null    object
 3   review_id          150 non-null    object
 4   product_id         150 non-null    object
 5   product_parent     150 non-null    int64
 6   product_title      150 non-null    object
 7   product_category   150 non-null    category
 8   star_rating        150 non-null    int64
 9   helpful_votes      150 non-null    int64
 10  total_votes        150 non-null    int64
 11  vine               150 non-null    bool
 12  verified_purchase  150 non-null    bool
 13  review_headline    150 non-null    object
 14  review_body        150 non-null    object
dtypes: bool(2), category(2), datetime64[ns](1), int64(4), object(6)
memory usage: 14.9+ KB

In [ ]:
display(df)

,review_date,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_year,review_month,review_body_raw
0,1995-06-24,US,53096571,RHL4UW17ZK72A,521314925,981000000,Invention and Evolution:Design in Nature and E...,Books,5,9,9,False,False,buy this book,this is a beautiful book french talks about en...,1995,6,This is a beautiful book. French talks about e...
1,1995-06-24,US,53096571,R34N4QWDXX58WB,870210092,443000000,"Arming and Fitting of English Ships of War, 16...",Books,4,12,13,False,False,good enough to understand all of pat obrien,nice diags lucid explanations of rigging guns ...,1995,6,"Nice diags, lucid explanations of rigging, gun..."
2,1995-07-07,US,53096573,RPLV77JZXG575,047194128X,377000000,Object-Oriented Type Systems,Books,4,4,4,False,False,good techniques well written,the best and possibly only book ive seen on th...,1995,7,The best (and possibly only) book I've seen on...
3,1995-07-18,US,53011769,R33HOJ2OWJIDQI,089145537X,837000000,The Collector's Guide to Harker Pottery U.S.A....,Books,5,27,27,False,False,the definitive volume on harker pottery,ok im biased my mother wrote this one many of ...,1995,7,"OK, I'm biased. My mother wrote this one. Many..."
4,1995-07-19,US,53096552,R3SM9591SGTMJ,517593483,114000000,Fingerprints Of The Gods: The Evidence of Eart...,Books,5,0,1,False,False,this book will open your mind to the past exce...,the author has a keen sense of how to unfold h...,1995,7,The author has a keen sense of how to unfold h...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,1995-11-21,US,53095692,RQR7102OERFLE,553299077,87417247,The Face of the Waters,Books,5,0,0,False,False,would have made a better screenplay than water...,one of agbergs best a wonderfully lucid view o...,1995,11,One of AGbergs best! A wonderfully lucid view ...
147,1995-11-22,US,53096316,R3RRC9ZELZT51B,676312977,178447398,Hero and the Crown,Books,1,13,33,False,False,read it aloud yourself instead,the book in print is magical evocative and lyr...,1995,11,"The book in print is magical, evocative, and l..."
148,1995-11-22,US,53073385,R3IJ91HHIWFF81,848808169,150825861,These Old Shades,Books,5,24,25,False,False,heyers best charming witty full of humor,for a lighthearted read this is one of the mos...,1995,11,"For a light-hearted read, this is one of the m..."
149,1995-11-22,US,53096008,R12YVQ9SW06GA7,805240616,710501777,The Five Books of Moses: The Schocken Bible: V...,Books,5,9,9,False,False,a major translation of the first five books of...,a glorious book that is magnificently printed ...,1995,11,A glorious book that is magnificently printed....
150,1995-11-24,US,53095677,R2XVQZDED8Q2H5,910311978,360983853,En Route to Global Occupation,Books,5,13,16,False,False,ready for the federation of earth and a new co...,this book reads like a journey of an author wh...,1995,11,This book reads like a journey of an author wh...

In [ ]:
# df[df['review_date'].isna()]  # Should return empty if all dates are valid.
df[df['helpful_votes'] < 0]  # Votes should never be negative.

Empty DataFrame
Columns: [review_date, marketplace, customer_id, review_id, product_id, product_parent, product_title, product_category, star_rating, helpful_votes, total_votes, vine, verified_purchase, review_headline, review_body, review_year, review_month, review_body_raw]
Index: []

In [ ]:
# Check uniqueness ratio (if < 10%, likely categorical)
print(df['marketplace'].nunique() / len(df))  # e.g., 3/151 = 2% → categorical
print(df['product_category'].nunique() / len(df))  # e.g., 5/151 = 3.3% → categorical
print(df['review_body'].nunique() / len(df))  # e.g., 150/151 = 99% → NOT categorical

0.006622516556291391
0.019867549668874173
0.9933774834437086

In [ ]:
!pip install mysql-connector-python

In [ ]:
!pip install pymysql pandas sqlalchemy

In [ ]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd

TIDB_CONFIG = {
    'host': 'gateway01.ap-southeast-1.prod.aws.tidbcloud.com',  # Replace with your TiDB host
    'port': 4000,
    'user': '2Z7qHQGegXYsM37.root',
    'password': 'i72ndKfsbA4ZiEgu',
    'database': 'aws_datas',
    'ssl_verify_cert': True,  # Enable SSL verification
    'ssl_ca': '/content/isrgrootx2.pem'  # Path to CA certificate (if required)
}

In [ ]:

connection_string = (
    f"mysql+pymysql://{TIDB_CONFIG['user']}:{TIDB_CONFIG['password']}"
    f"@{TIDB_CONFIG['host']}:{TIDB_CONFIG['port']}/{TIDB_CONFIG['database']}"
    "?ssl_ca=/path/to/ca.pem&ssl_verify_cert=true"
)

engine = create_engine(connection_string)

In [ ]:

# Automatically creates a table matching the DataFrame structure
df.to_sql('product_reviews', con=engine, if_exists='replace', index=False)
print("Inserted into sql successfully")

Inserted into sql successfully

In [ ]:
# Identify the products with the highest number of reviews.
query = """
SELECT
    product_id,
    product_title,
    COUNT(*) AS review_count,
    AVG(star_rating) AS avg_rating
FROM
    product_reviews
GROUP BY
    product_id, product_title
ORDER BY
    review_count DESC
LIMIT 10;
"""

top_products_df = pd.read_sql(query, engine)
display(top_products_df)

,product_id,product_title,review_count,avg_rating
0,713724935,Ufo Retrievals: The Recovery of Alien Spacecraft,2,5.0
1,B000002OTL,Pulp Fiction: Music From The Motion Picture,1,5.0
2,1560548908,Angel Maker,1,5.0
3,553263285,"A Darkness at Sethanon (The Riftwar Saga, Vol. 4)",1,5.0
4,786000716,For the Love of You (Arabesque),1,5.0
5,446400068,Drowned Hopes,1,5.0
6,811208478,Journey to the End of the Night (English and F...,1,5.0
7,380710218,Post-mortem,1,5.0
8,096309212X,Radical Honesty (How to Transform Your Life By...,1,5.0
9,1556113560,The Gun Ketch,1,5.0